### 测试创建学生
POST http://localhost:8080/user/student
Content-Type: application/json

{
  "name": "testStudent",
  "password": "password123",
  "role": "student",
  "enrollment_year": "2024",
  "major": "Computer Science",
  "student_group": "Software Engineering 4"
}
###